Q02
hanlonjohn23/scala-challenge pull request #2
Opened 2022-02-10 22:21 UTC by jhanlonhg

Second Code Challenge.

### Notes
#### Error Handling
Not sure what is the best way to throw and handle errors, namely in [HttpRequestor](https://github.com/jhanlonhg/scala-challenge/compare/develop...q02#diff-d40692d2f835b6e3cb99fbc6fa0bbbce5ccc56a2e8fc4c44baa2d127be9b8e7fR42) and [Main](https://github.com/jhanlonhg/scala-challenge/compare/develop...q02#diff-a8c936a27247452dcd65a1c15bf1b96626ca6f026fbf345cac89d5fd3c69a2d6R15). Both these errors should be breaking, since they are a response error and a input error, respectively.

#### Bad Patterns
[This solution](https://github.com/jhanlonhg/scala-challenge/compare/develop...q02#diff-a8c936a27247452dcd65a1c15bf1b96626ca6f026fbf345cac89d5fd3c69a2d6R15) does not have a great smell, and I am not sure what would be a better solution.

#### Testing
I have tried to cover the test cases that I believe are relevant. I do have two outstanding questions:
1. What testing, if any, should be done for the `ArgParser` & `HttpReqester` classes? For the `ArgParser`, I feel any test would simply be testing the ScalaJ library, and for the `ArgParser` I feel that any tests would simply be pinging the Geocoder API, which is not under the purview of unit tests.
2. What is the rule of thumb for private methods? Should they have individual tests ([scalatest supports this](https://www.scalatest.org/user_guide/using_PrivateMethodTester)) or should they be tested by virtue of testing public methods?

2022-02-11 00:18 UTC, sbchapin requested changes

2022-02-11 00:18 UTC, sbchapin commented on build.sbt
> +    assembly / assemblyJarName := "q02.jar"
Note that an alternative to this would be to create [a multiproject build](https://www.scala-sbt.org/1.x/docs/Multi-Project.html) which would allow you to build independent jars and specify dependencies to each independently, allowing your old adder to exist alongside the new program.  Each jar would contain only each entrypoint and any shared code, separated by project.

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/HttpRequester.scala
> +                           )
This contract is brittle.  You've specified `staddress`, `stnumber`,  `confidence`, and `postal`,  but done nothing with them (with the downside of making testing more difficult in addition to brittleness).  In reality, the only things you actually need are the `city` and `prov`.

The answer to making this less brittle lies in circe and its decoders.  You've relied on the semiautomatic derivation for `StandardObject`, but I would suggest writing something custom.

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/HttpRequester.scala
> +                                   remaining_credits: String
Similar comment here for `remaining_credits`

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/HttpRequester.scala
> +    implicit val gcResponseDecoder: Decoder[GeocoderResponseBody] = deriveDecoder[GeocoderResponseBody]
Move these implicit vals out of the method.  No need to derive the decoders every time you do a request, as their definition will not change based on any parameterization - you really only need to derive them once as they depend on no parameters at all, so you may as well move em out to the scope of the HttpRequester object.

In fact, it may make sense to move them directly to companion objects for their respective classes.  But it would only make sense to do so if you put those classes in a separate module.  Telling is difficult - I'll show you why.  Grab me if/when you want to go through that.

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/LeastDistanceCalculator.scala
> +  }
Nice usage of recursion and of type parameters here.  Dig the implementation.

---

Minor quip: I would change either the signature or the name of `generatePairs`.  It shares the same naming convention and similar signature to `generateDistinctPairs`, but its functionality and usage of head/tail is pretty different from what I would expect.

For instance, `generateDistinctPairs` will generate all distinct sets of all combinations `(a, b, c) -> (a, b), (a, c), (b, c)`, while `generatePairs` will only generate a set of the first element coupled with the rest `(a, b, c) -> (a, b), (a, c) not (b, c)`.

To distinguish the two, I'd suggest either renaming it to highlight functionality, or use a separate type signature and parameters like...
```scala
def generatePairs(left: A, rights: Seq[A]): Seq[(A, A)] = ???
```

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/LeastDistanceCalculator.scala
> +    val distanceBetween: Double = sqrt(pow(location1.longitude - location2.longitude, 2) + pow(location1.latitude - location2.latitude, 2))
[This is how I know you're a flat-earther.](https://en.wikipedia.org/wiki/Haversine_formula)

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/LeastDistanceCalculator.scala
> +    val location2 = locationPair._2
```suggestion
    val (location1, location2) = locationPair
```

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/LeastDistanceCalculator.scala
> +                   )
This is a very subjective comment, but has a lot to do with how you wrap data (and the relationships between domain objects):

Should a "Distance" have two locations?  Should a "Location" have distances?  Should `getClosestCities` return a Distance, or should it return Locations?

Generally, the answer to these questions can be varied and is nearly always dependent on your domain and how you need to represent it, but I generally find I am drawn to tuples if the context that binds objects together is varied and not often re-used (as I suspect this one may be).  

Specifically, `def getClosestCities(locations: Seq[Location]): (Location, Location)` satisfies the constraints of your program, and back-propagating that will eliminate some unnecessary code.

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/LeastDistanceCalculator.scala
> +  }
There are more complex answers to this if you are doing lensing or some other tricky operations, but I'll give you the simple one for now:  Recognize when a problem doesn't need the power of pattern matching.

```scala
  private def getMinDistance(distance1: Distance, distance2: Distance): Distance = {
    if (distance1.length < distance2.length) {
      distance1
    } else {
      distance2
    }
  }
```

2022-02-11 00:18 UTC, sbchapin commented on src/test/scala/LeastDistanceCalculatorTest.scala
> +      == List(("a", "b"), ("a", "c"), ("b", "c")))
Something inadvertently being tested here is ordering.  I don't think it's a big deal, but it does mean this test could break unintentionally if your implementation changes the ordering of pairs (either within the list or within the pairs themselves).

2022-02-11 00:18 UTC, sbchapin commented on src/main/scala/Location.scala
> +      longitude = gcrb.longt.toDouble
`toDouble` is a dangerous operation on a String.  Given that dealing with this failing is really the responsibility of the deserialization layer, I would suggest moving it there.

2022-02-11 00:21 UTC, jhanlonhg commented on src/main/scala/LeastDistanceCalculator.scala
> +    val distanceBetween: Double = sqrt(pow(location1.longitude - location2.longitude, 2) + pow(location1.latitude - location2.latitude, 2))
I also assume there is no friction too

2022-02-11 01:20 UTC, sbchapin commented
> ###
> #### Error Handling
> Not sure what is the best way to throw and handle errors, namely in [HttpRequestor](https://github.com/jhanlonhg/scala-challenge/compare/develop...q02#diff-d40692d2f835b6e3cb99fbc6fa0bbbce5ccc56a2e8fc4c44baa2d127be9b8e7fR42) and [Main](https://github.com/jhanlonhg/scala-challenge/compare/develop...q02#diff-a8c936a27247452dcd65a1c15bf1b96626ca6f026fbf345cac89d5fd3c69a2d6R15). Both these errors should be breaking, since they are a response error and a input error, respectively.

There are a few ways to fail, though I would argue that a response failing should not be a halting failure.

The safe way is to accept failure and provide a way around - this may be something like trying and returning `Some(thing)`, or catching, logging, and returning `None`.  Only do this if you can truly afford to fail and default, otherwise you're no better off than the same suppression pattern in java.

The "functional" way generally depends on `Try[T]` or `Either[L, R]` where [right conventionally means success](https://www.scala-lang.org/api/2.12.7/scala/util/Either.html).

The "exceptional" way generally depends on RuntimeExceptions being thrown, but the downside is that any function can fail from anywhere with a RuntimeException, which is generally a bad thing.

Generally, I tend to push failure to places that should be able to fail, and keep that failure there and test it.  In your case, I imagine an `HttpRequestor` encapsulating that failure in its response rather than escalating it.  I also imagine moving the `IllegalArgumentException` from Main up into to the arg parser where it is actually failing (from a responsibility perspective) - enforce that the arguments have `cities: Seq[String]` and do the parsing immediately in the arg parser.

> #### Bad Patterns
> [This solution](https://github.com/jhanlonhg/scala-challenge/compare/develop...q02#diff-a8c936a27247452dcd65a1c15bf1b96626ca6f026fbf345cac89d5fd3c69a2d6R15) does not have a great smell, and I am not sure what would be a better solution.

I didn't want to go crazy with the answer [here](https://github.com/jhanlonhg/scala-challenge/pull/2#discussion_r804246954), but if you want a further explanation, please ask.

> #### Testing
> I have tried to cover the test cases that I believe are relevant. I do have two outstanding questions:
> 
> 1. What testing, if any, should be done for the `ArgParser` & `HttpReqester` classes? For the `ArgParser`, I feel any test would simply be testing the ScalaJ library, and for the `ArgParser` I feel that any tests would simply be pinging the Geocoder API, which is not under the purview of unit tests.
> 2. What is the rule of thumb for private methods? Should they have individual tests ([scalatest supports this](https://www.scalatest.org/user_guide/using_PrivateMethodTester)) or should they be tested by virtue of testing public methods?

1. I would test the "good paths" of `ArgParser` behaviorally.  You want the Arguments instance to contain formatted, parsed values.  That way you can swap your arg parser library out whenever you want, since none of its implementation details are really leaking.  `HttpRequester` can [be mocked](https://www.scalatest.org/user_guide/testing_with_mock_objects), but I personally find a rather marginal amount of value in that.
2. Don't test private methods.  At worst, test protected or package-local methods, but avoid it.  If something is sufficiently complicated enough that testing many of the edge cases within private methods is difficult, consider splitting your solution into smaller pieces, each of which can be tested (then, behaviorally test them all together re-assembled).

2022-02-11 01:28 UTC, sbchapin commented on src/main/scala/LeastDistanceCalculator.scala
> +    val distanceBetween: Double = sqrt(pow(location1.longitude - location2.longitude, 2) + pow(location1.latitude - location2.latitude, 2))
Also a problem is negative/positive lat/lon.

Here's a good testcase for you: 

 What is closer?
- [Adak, Alaska United States](https://www.google.com/maps/search/?api=1&query=Adak%2C%20Alaska%20United%20States)Coordinates: 51°53′N 176°39′W
- [Anadyr, Chukotka Autonomous Okrug Russia](https://www.google.com/maps/search/?api=1&query=Anadyr%2C%20Chukotka%20Autonomous%20Okrug%20Russia), Coordinates: 64°44′N 177°31′E
- Los Angeles?

Basically, the edge-cases where lat/long wrap around.  [Use this](https://blog.batchgeo.com/cities-by-latitude-and-longitude/) to find out.

2022-02-11 22:08 UTC, hanlonjohn23 commented on src/main/scala/HttpRequester.scala
> +                           )
This structure has replaced with the Location object, which only contains relevant information.

2022-02-11 22:08 UTC, jhanlonhg commented on src/main/scala/HttpRequester.scala
> +                                   remaining_credits: String
This structure has replaced with the Location object, which only contains relevant information.

2022-02-11 22:14 UTC, jhanlonhg commented on src/main/scala/LeastDistanceCalculator.scala
> +  }
Changed the name and the signature!

2022-02-11 23:56 UTC, jhanlonhg commented on src/main/scala/LeastDistanceCalculator.scala
> +                   )
Made Distance a private member

2022-02-11 23:56 UTC, jhanlonhg commented on src/main/scala/LeastDistanceCalculator.scala
> +  }
👍

2022-02-14 18:10 UTC, hanlonjohn23 commented on src/main/scala/HttpRequester.scala
> +    implicit val gcResponseDecoder: Decoder[GeocoderResponseBody] = deriveDecoder[GeocoderResponseBody]
Resolved by using a custom decoder, and calling that decoder in a higher scope.

2022-02-14 18:33 UTC, jhanlonhg commented on src/main/scala/LeastDistanceCalculator.scala
> +    val distanceBetween: Double = sqrt(pow(location1.longitude - location2.longitude, 2) + pow(location1.latitude - location2.latitude, 2))
Updated code to use Haversine Distance calculations, and added a test for distances over the 180th meridian.

2022-02-14 20:24 UTC, sbchapin approved these changes
Solid.

2022-02-14 20:24 UTC, sbchapin commented on src/test/scala/LeastDistanceCalculatorTest.scala
> +  }
In love with these tests

2022-02-14 20:24 UTC, sbchapin commented on src/test/scala/LocationTest.scala
> +    assert(decode[Location](geocoderResponseBody).right.getOrElse() == location)
Alternatively, 
```scala
assert(decode[Location](geocoderResponseBody) == Right(location))
```

Then it will tell you what things both didn't equal rather than just exception barfing on getOrElse()

2022-02-14 21:42 UTC, hanlonjohn23 commented on src/test/scala/LocationTest.scala
> +    assert(decode[Location](geocoderResponseBody).right.getOrElse() == location)
Great advice. Implemented.

2022-02-14 21:42 UTC, jhanlonhg commented on src/test/scala/LeastDistanceCalculatorTest.scala
> +  }
Pretty proud myself

2022-02-14 21:43 UTC, jhanlonhg commented on src/main/scala/Location.scala
> +      longitude = gcrb.longt.toDouble
Resolved as advised.

2022-02-14 22:12 UTC, merged